# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-19 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangoapp', '0009_userprofile_category_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=200),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(default=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='category_like',
            field=models.ManyToManyField(blank=True, related_name='category_like', to='rangoapp.Category'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
