# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangoapp', '0010_auto_20171019_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deslikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category_deslike',
            field=models.ManyToManyField(blank=True, related_name='category_deslike', to='rangoapp.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
