# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangoapp', '0011_auto_20171020_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='page_deslike',
            field=models.ManyToManyField(blank=True, related_name='page_deslike', to='rangoapp.Page'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='page_like',
            field=models.ManyToManyField(blank=True, related_name='page_like', to='rangoapp.Page'),
        ),
    ]
