# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangoapp', '0012_auto_20171024_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
