# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangoapp', '0013_page_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='deslikes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
